cpp/urls.py
from django.urls import path
from . import views
app_name = 'cpp'
urlpatterns = [

    path('',views.topics,name='all_topics'),

    path('<int:topic_id>/', views.detail, name='detail'),

]

know_python/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from home import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.about,name='about'),
    path('contact/', views.contact, name='contact'),

    path('python/', include('topics.urls')),
    path('cpp/', include('cpp.urls')),

]
urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

topics/urls.py
from django.urls import path
from . import views
app_name = 'topics'
urlpatterns = [

    path('',views.topics,name='all_topics'),

    path('<int:topic_id>/', views.detail, name='detail'),

]

cpp/models.py
from django.db import models

class Cpp(models.Model):
    title=models.CharField(max_length=100)
    detail=models.TextField()

    def __str__(self):
        return self.title

home/models.py
from django.db import models

class Tutorial(models.Model):
    title=models.CharField(max_length=100)
    description=models.CharField(max_length=250)
    image=models.ImageField(upload_to='topics/images/')
    url=models.URLField(blank=True)

    def __str__(self):
        return self.title

topics/models.py
from django.db import models

class Topic(models.Model):
    title=models.CharField(max_length=100)
    detail=models.TextField()

    def __str__(self):
        return self.title

cpp/views.py
from django.shortcuts import render,get_object_or_404
from django.core.paginator import Paginator
from .models import Cpp

def topics(request):
    topics=Cpp.objects.all().order_by('id')
    paginator=Paginator(topics,5)
    page_number=request.GET.get('page')
    page_obj=paginator.get_page(page_number)
    return render(request,'cpp/topic.html',{'topics':page_obj})

def detail(request,topic_id):
    topic=get_object_or_404(Cpp,pk=topic_id)
    return render(request,'cpp/detail.html',{'topic':topic})

home/views.py
from django.shortcuts import render
from .models import Tutorial

def about(request):
    tutorials=Tutorial.objects.all()
    return render(request,'home/about.html',{'tutorials':tutorials})

def contact(request):
    return render(request,'home/contact.html')

topics/views.py
from django.shortcuts import render,get_object_or_404
from django.core.paginator import Paginator
from .models import Topic

def topics(request):
    topics=Topic.objects.all().order_by('id')
    paginator=Paginator(topics,5)
    page_number=request.GET.get('page')
    page_obj=paginator.get_page(page_number)
    return render(request,'topics/topic.html',{'topics':page_obj})

def detail(request,topic_id):
    topic=get_object_or_404(Topic,pk=topic_id)
    return render(request,'topics/detail.html',{'topic':topic})

cpp/templates/cpp/detail.html
{%extends 'home/base.html'%}
{%block content%}
<h1 id="hometext">{{topic.title}}</h1>
{{topic.detail|safe}}
{%endblock%}

cpp/templates/cpp/topic.html
{%extends 'home/base.html'%}
{%block content%}

{%for topic in topics%}
<a href="{%url 'cpp:detail' topic.id%}"><h1>{{topic.title}}</h1></a>
<p>{{topic.detail|striptags|truncatechars:100}}</p>
{%endfor%}
<div class="pagination">
    <span class="step-links">
        {% if topics.has_previous %}
            <a href="?page=1">&laquo; first</a>
        <br>
            <a href="?page={{ topics.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ topics.number }} of {{ topics.paginator.num_pages }}.
        </span>

        {% if topics.has_next %}
            <a href="?page={{ topics.next_page_number }}">next</a>
        <br>
            <a href="?page={{ topics.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
{%endblock%}

home/templates/home/about.html
{%extends 'home/base.html'%}
{%load static%}
{%block content%}
<h1 id="hometext" class="text-dark text-center text-uppercase bg-light mb-5">Welcome to hack code!</h1>
<div class="row justify-content-center my-3">
    <div class="col-5">
<img src="{%static 'home/company.jpg'%}" alt="Responsive image" class="img-fluid mb-5" >
</div>
</div>
<div class="row">
    {%for tutorial in tutorials%}
    <div class="col-lg-4 col-md-6 col-6">
        <h1>{{tutorial.title}}</h1>
<p>{{tutorial.description}}</p>
        <img src="{{tutorial.image.url}}" class="img-fluid mb-5 img-thumbnail">
{%if tutorial.url%}
<a href="{{tutorial.url}}">link</a>
{%endif%}
    </div>


{%endfor%}

</div>

{%endblock%}

home/templates/home/base.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
{%load static%}
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Didact+Gothic&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{%static 'home/style.css'%}">
    <title>Hack code</title>
  </head>
  <body>
    <div class="container-fluid">
  <nav class="navbar navbar-expand-lg navbar-light bg-warning mb-2">

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{%url 'about'%}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{%url 'contact'%}">contact us</a>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          learn
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="{%url 'topics:all_topics' %}">learn python</a>
            <a class="dropdown-item" href="{%url 'cpp:all_topics' %}">learn c++</a>
        </div>
      </li>


    </ul>



  </div>
</nav>


    {%block content%}{%endblock%}
  </div>


    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

home/templates/home/contact.html
{%extends 'home/base.html'%}
{%block content%}
<h1 class="text-success">contact us at 00110022007</h1>
{%endblock%}

topics/templates/topics/detail.html
{%extends 'home/base.html'%}
{%block content%}
<h1 id="hometext">{{topic.title}}</h1>
{{topic.detail|safe}}
{%endblock%}

topics/templates/topics/topic.html
{%extends 'home/base.html'%}
{%block content%}

{%for topic in topics%}
<a href="{%url 'topics:detail' topic.id%}"><h1>{{topic.title}}</h1></a>
<p>{{topic.detail|striptags|truncatechars:100}}</p>
{%endfor%}
<div class="pagination">
    <span class="step-links">
        {% if topics.has_previous %}
            <a href="?page=1">&laquo; first</a>
        <br>
            <a href="?page={{ topics.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ topics.number }} of {{ topics.paginator.num_pages }}.
        </span>

        {% if topics.has_next %}
            <a href="?page={{ topics.next_page_number }}">next</a>
        <br>
            <a href="?page={{ topics.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
{%endblock%}